CREATE TABLE Technician (
	TechnicianID int GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
	Name varchar(255)
);

/*hiii*/

CREATE TABLE Airplane (
	AirplaneID int GENERATED BY DEFAULT AS IDENTITY (START WITH 10) PRIMARY KEY, 
	Name varchar(255),
	Manufacturer varchar(255),
	Engines varchar(255),
	RangeKm int,
	CargoCapacityKg int, 
	FuelCapacityL int,
	AirplaneLengthM int,
	WingSpanM int
);

CREATE TABLE Warranty (
	WarrantyID int GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
	AirplaneID_FK int,
	Status varchar(255),
	CONSTRAINT fk_Airplane
    FOREIGN KEY (AirplaneID_FK)
    REFERENCES Airplane(AirplaneID)
);

CREATE TABLE WarrantyEvent (
	WEventID int GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
	WarrantyID_FK int,
	TechnicianID_FK int,
	AirplaneID_FK int,
	Description varchar(255),
	Image BYTEA,
	CONSTRAINT fk_Warranty
    FOREIGN KEY (WarrantyID_FK)
    REFERENCES Warranty(WarrantyID),
	
	CONSTRAINT fk_Technician_WarrantyEvent
    FOREIGN KEY (TechnicianID_FK)
    REFERENCES Technician(TechnicianID),

	CONSTRAINT fk_Airplane_WarrantyEvent
    FOREIGN KEY (AirplaneID_FK)
    REFERENCES Airplane(AirplaneID)	
);

CREATE TABLE MaintenanceEvent (
	MEventID int GENERATED BY DEFAULT AS IDENTITY (START WITH 10000) PRIMARY KEY,
	TechnicianID_FK int,
	AirplaneID_FK int,
	Type varchar(255),
	Description varchar(255),	
	CONSTRAINT fk_Technician_MaintenanceEvent
    FOREIGN KEY (TechnicianID_FK)
    REFERENCES Technician(TechnicianID),

	CONSTRAINT fk_Airplane_MaintenanceEvent
    FOREIGN KEY (AirplaneID_FK)
    REFERENCES Airplane(AirplaneID)
);